const QuoteLs = [
    "A reader lives a thousand lives before he dies.", 
    "Life can only be understood backwards, but it must be lived forwards.",
    "The happiness of the wise grows out of their own free acts.",
    "Be on of the best in your field and the money will find you.",
    "It's not where you start, it's where you finish.",
    "Working out should not be a punishment for what you eat, but a celebration for what you can achieve.",
    "Disappointment is part of the road to greatness, always ask yourself, what did you learn from this effort.",
    "Become at peace with the noise, find your soft zone.",
    "Always seek out challenges, never avoid them.",
    "Failure is not a negative.",
    "When we make a mistake and get frozen in what was, a layer of detachment in the now builds.",
    "Embrace transition.",
    "Spur growth, but maintain balance.",
    "You have to lose to incur growth, don't let ego get in the way.",
    "Constant supply of a stimulus turns us into addicts.",
    "Depth beats breath, depth opens the channel for our unconscious creative components that allow us to reach hidden potential.",
    "Flow with distraction.",
    "Have a solid foundation, then use this foundation to take on difficult scenarios.",
    "Take a single idea and practice it, practice enough to add it to your invisible arsenal.",
    "We're (gods) the dreams that humanity created to make sense of the shadows on the cave walls.",
    "Call no man happy until he is dead, don't judge the shape of someone's life.",
    "People react to fear, not love.",
    "Others may hate you, but those who hate you don't win until you hate them and destroy yourself.",
    "The Earth is a generous mother, she will provide plentiful abundance food for all her children, if they cultivate her soil in justice and peace.",
    "As a person's time and effort accumulate, others who spent less time are likely to call this person talented.",
    "A man's true potential comes when his various talents and knowledge are fully utilized to create value for others.",
    "It's easier to say there's something wrong with me, then admitting you need to improve.",
    "Don't lose hope, celebrate progress and fight for more.",
    "Media relies on drama for attention.",
    "Expect bad news, good news is never news.",
    "No room for facts when our minds are occupied by fear.",
    "All those things you are afraid of, murder plane crash, terrorism none of thtem kill more than 1 percent of people per year. Victims of drunk driving kill more, but drunk driving isn't dramatic so it's not reported",
    "Focus on the dangers of today, not the past.",
    "Be calm before carrying on.",
    "Slow change is still change.",
    "Problems are complex, not simple. Think at many angles and solve them case by case.",
    "Look for causes or systems, not villains.",
    "Data should tell the truth, not call for action.",
    "Human beings are the sex organs of the machine world.",
    "Being humble means you can stop feeling pressured to have a view about everything and stop feeling the necessity to defend your views all the time.",
    "Be curious, be open to new information and actively seek it out.",
    "Be uncommon amongst the uncommon.",
    "War is a way of destroying materials that might otherise be used for good.",
    "Complain less, enjoy more.",
    "Confidence doesn't come from assurance.",
    "Have some curosity, be less concerned with what other people think.",
    "Just open up and let someone in, whatever comes after you face it together.",
    "Large circle to smaller circles.",
    "Most men and women by birth or nature, lack the means to advance in wealth and power, but all have the ability to advance in knowledge.",
    "If more of us valued food and cheer and song above hordes of gold, it would be a merrier world."
]

export default QuoteLs